# Generated by Django 5.0.6 on 2024-07-22 12:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('module_du_cours', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('leçon', 'Leçon'), ('devoir', 'Devoir')], default='leçon', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('document', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='CoursesUpload/pdfs/'), upload_to='pdfs/')),
            ],
        ),
    ]
